SRCS  = PVRGUIInfo.cpp
SRCS += PVRManager.cpp
SRCS += PVRDatabase.cpp
SRCS += PVRActionListener.cpp

LIB   = pvr.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
