SRCS  = DirectoryNode.cpp
SRCS += DirectoryNodeEpisodes.cpp
SRCS += DirectoryNodeGrouped.cpp
SRCS += DirectoryNodeMoviesOverview.cpp
SRCS += DirectoryNodeMusicVideosOverview.cpp
SRCS += DirectoryNodeOverview.cpp
SRCS += DirectoryNodeRecentlyAddedEpisodes.cpp
SRCS += DirectoryNodeRecentlyAddedMovies.cpp
SRCS += DirectoryNodeRecentlyAddedMusicVideos.cpp
SRCS += DirectoryNodeRoot.cpp
SRCS += DirectoryNodeSeasons.cpp
SRCS += DirectoryNodeTitleMovies.cpp
SRCS += DirectoryNodeTitleMusicVideos.cpp
SRCS += DirectoryNodeTitleTvShows.cpp
SRCS += DirectoryNodeTvShowsOverview.cpp
SRCS += QueryParams.cpp

LIB   = videodatabasedirectory.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
