SRCS  = GUIDialogAudioDSPManager.cpp
SRCS += GUIDialogAudioDSPSettings.cpp
SRCS += GUIDialogContentSettings.cpp
SRCS += GUIDialogSettingsBase.cpp
SRCS += GUIDialogSettingsManagerBase.cpp
SRCS += GUIDialogSettingsManualBase.cpp

LIB   = settings_dialogs.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
