SRCS  = GUIViewControl.cpp
SRCS += GUIViewState.cpp
SRCS += ViewDatabase.cpp
SRCS += ViewStateSettings.cpp

LIB   = view.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))