SRCS  = GUIViewStatePVR.cpp
SRCS += GUIWindowPVRBase.cpp
SRCS += GUIWindowPVRChannels.cpp
SRCS += GUIWindowPVRGuide.cpp
SRCS += GUIWindowPVRRecordings.cpp
SRCS += GUIWindowPVRSearch.cpp
SRCS += GUIWindowPVRTimers.cpp

LIB   = pvrwindows.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
