SRCS  = GUIDialogAudioSubtitleSettings.cpp
SRCS += GUIDialogFullScreenInfo.cpp
SRCS += GUIDialogSubtitles.cpp
SRCS += GUIDialogTeletext.cpp
SRCS += GUIDialogVideoBookmarks.cpp
SRCS += GUIDialogVideoInfo.cpp
SRCS += GUIDialogVideoOSD.cpp
SRCS += GUIDialogVideoSettings.cpp

LIB   = videodialogs.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
