SRCS  = GUIDialogPVRChannelManager.cpp
SRCS += GUIDialogPVRChannelsOSD.cpp
SRCS += GUIDialogPVRGroupManager.cpp
SRCS += GUIDialogPVRGuideInfo.cpp
SRCS += GUIDialogPVRGuideOSD.cpp
SRCS += GUIDialogPVRGuideSearch.cpp
SRCS += GUIDialogPVRRadioRDSInfo.cpp
SRCS += GUIDialogPVRRecordingInfo.cpp
SRCS += GUIDialogPVRTimerSettings.cpp

LIB   = pvrdialogs.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
