SRCS  = GUIWindowMusicBase.cpp
SRCS += GUIWindowMusicNav.cpp
SRCS += GUIWindowMusicPlaylist.cpp
SRCS += GUIWindowMusicPlaylistEditor.cpp
SRCS += GUIWindowMusicSongs.cpp

LIB   = musicwindows.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
