SRCS  = GUIWindowFullScreen.cpp
SRCS += GUIWindowVideoBase.cpp
SRCS += GUIWindowVideoNav.cpp
SRCS += GUIWindowVideoPlaylist.cpp

LIB   = videowindows.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
