SRCS  = GUIDialogPeripheralSettings.cpp
SRCS += GUIDialogPeripheralManager.cpp

LIB   = peripheral-dialogs.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
