SRCS  = GUIDialogMusicInfo.cpp
SRCS += GUIDialogMusicOSD.cpp
SRCS += GUIDialogSongInfo.cpp

LIB   = musicdialogs.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
