SRCS  = GUIDialogBoxBase.cpp
SRCS += GUIDialogBusy.cpp
SRCS += GUIDialogButtonMenu.cpp
SRCS += GUIDialogCache.cpp
SRCS += GUIDialogContextMenu.cpp
SRCS += GUIDialogExtendedProgressBar.cpp
SRCS += GUIDialogFavourites.cpp
SRCS += GUIDialogFileBrowser.cpp
SRCS += GUIDialogGamepad.cpp
SRCS += GUIDialogKaiToast.cpp
SRCS += GUIDialogKeyboardGeneric.cpp
SRCS += GUIDialogMediaFilter.cpp
SRCS += GUIDialogMediaSource.cpp
SRCS += GUIDialogMuteBug.cpp
SRCS += GUIDialogNumeric.cpp
SRCS += GUIDialogOK.cpp
SRCS += GUIDialogPlayEject.cpp
SRCS += GUIDialogPlayerControls.cpp
SRCS += GUIDialogProgress.cpp
SRCS += GUIDialogSeekBar.cpp
SRCS += GUIDialogSelect.cpp
SRCS += GUIDialogSimpleMenu.cpp
SRCS += GUIDialogSlider.cpp
SRCS += GUIDialogSmartPlaylistEditor.cpp
SRCS += GUIDialogSmartPlaylistRule.cpp
SRCS += GUIDialogSubMenu.cpp
SRCS += GUIDialogTextViewer.cpp
SRCS += GUIDialogVolumeBar.cpp
SRCS += GUIDialogYesNo.cpp

LIB   = dialogs.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
